name: Docker image

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            airndlab/hackathon-hacks-ai-2023-vanilla-ranker-service:${{ github.ref_name }}
            airndlab/hackathon-hacks-ai-2023-vanilla-ranker-service:latest
